runtime: custom
env: flex
service: front-end
resources:
  cpu: 1
  memory_gb: 1
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.75
  target_concurrent_requests: 100
liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  initial_delay_check: 30
readiness_check:
  path: "/"
  check_interval_sec: 5
  timeout_sec: 5
  failure_threshold: 5
  success_threshold: 2
  app_start_timout_sec: 100
