apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: front-end
spec:
  template:
    spec:
      containers:
      - image: gcr.io/bankingapplication/front-end:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        