apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  default.conf: "server {\r\n
\    listen 80;\r\n
\    server_name www.banking.jasonmarston.me.uk;\r\n
\r\n
\    location / {\r\n
\        root /usr/share/nginx/html;\r\n
\        index index.html;\r\n
\r\n
\        location /account {\r\n
\            proxy_pass http://account-svc:8080;\r\n
\        }\r\n
\r\n
\        location /user {\r\n
\            proxy_pass http://user-svc:8080;\r\n
\        }\r\n
\    }\r\n
}\r\n"
