steps:
- name: 'gcr.io/cloud-builders/gradle'
  args: ['build', 'artifactoryPublish']
  env:
  - 'artifactory_contextUrl=${_ARTIFACTORY_URL}'
  - 'artifactory_password=${_ARTIFACTORY_PASSWORD}'
  - 'artifactory_user=${_ARTIFACTORY_USER}'
  dir: 'user-domain'