apiVersion: v1
kind: Secret
metadata:
  name: account-env-secret
type: Opaque
stringData:
  BANKING_PROFILES_ACTIVE: DEV
  BANKING_DATASOURCE_DDL_AUTO: update
  BANKING_DATASOURCE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
  BANKING_LOGGING_LEVEL: WARN
  PUB_SUB_CREDENTIALS: file:/pubsub/pubsub.json
  GOOGLE_APPLICATION_CREDENTIALS: /firebase/firebase.json
  USER_DATASOURCE_URL: jdbc:mysql://localhost:3306/<user_database>?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=yes&characterEncoding=UTF-8
  ACCOUNT_DATASOURCE_URL: jdbc:mysql://localhost:3306/<account_database>?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=yes&characterEncoding=UTF-8
  BANKING_INITIAL_ADMIN_EMAIL: <admin_email_address>
  USER_DATASOURCE_USERNAME: <user_username>
  USER_DATASOURCE_PASSWORD: <user_password>
  ACCOUNT_DATASOURCE_USERNAME: <account_username>
  ACCOUNT_DATASOURCE_PASSWORD: <account_password>
